language: php

php:
  - 5.5
  - 5.6

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar config -g github-oauth.github.com $COMPOSEROAUTH
  - php composer.phar install
  - php -S localhost:8000 -t public public/index.php  > /dev/null &

after_script:
  - ./codeclimate.sh
 
script:
  - php vendor/bin/phpunit --coverage-clover logs/clover.xml
  - php vendor/bin/codecept run  --coverage --coverage-xml
